src/chapter6/beans/Message.java
package chapter6.beans;

import java.io.Serializable;
import java.util.Date;

public class Message implements Serializable {

	private int id;
	private String title;
	private String text;
	private String category;
	private int userId;
	private Date createdDate;
	private Date updatedDate;

	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}

	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}

	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}

	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}

src/chapter6/beans/UserComment.java
package chapter6.beans;
import java.io.Serializable;
import java.util.Date;

public class UserComment implements Serializable {

	private int id;
	private String text;
	private int userId;
	private int messageId;
	private Date createdDate;
	private Date updatedDate;
	private String name;
	private String account;

	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}

	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}

	// 追加したメソッド
    public String[] getSplitedText() {
        return text.split("\n");
    }

	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getMessageId() {
		return messageId;
	}
	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}

	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}

	public String getAccount() {
		return account;
	}
	public void setAccount(String account) {
		this.account = account;
	}

}

src/chapter6/controller/HomeServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import chapter6.beans.UserComment;
import chapter6.beans.UserMessage;
import chapter6.service.CommentService;
import chapter6.service.MessageService;

@WebServlet(urlPatterns = { "/" })
public class HomeServlet extends HttpServlet {

	@Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws IOException, ServletException {

		String start = request.getParameter("start");
		String end = request.getParameter("end");
		String category =request.getParameter("category");

		List<UserMessage> messages = new MessageService().select(start, end, category);
		List<UserComment> comments = new CommentService().select();

		request.setAttribute("messages", messages);
		request.setAttribute("comments", comments);
		request.setAttribute("start", start);
		request.setAttribute("end", end);
		request.setAttribute("category", category);

		request.getRequestDispatcher("/home.jsp").forward(request, response);

    }
}

src/chapter6/controller/LoginServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import chapter6.beans.User;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        request.getRequestDispatcher("login.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        String account = request.getParameter("account");
        String password = request.getParameter("password");

        User user = new UserService().select(account, password);

        if (user == null) {
        	List<String> errorMessages = new ArrayList<String>();
            errorMessages.add("アカウントまたはパスワードに誤りがあります");
            request.setAttribute("errorMessages", errorMessages);
            request.setAttribute("account",account);
            request.setAttribute("password", password);
            request.getRequestDispatcher("login.jsp").forward(request, response);
            return;
        }


        if ((user.getIsStopped()) ==1) {
            List<String> errorMessages = new ArrayList<String>();
            errorMessages.add("アカウントまたはパスワードに誤りがあります");
            request.setAttribute("errorMessages", errorMessages);
            request.getRequestDispatcher("login.jsp").forward(request, response);
            return;
        }

        HttpSession session = request.getSession();
        session.setAttribute("loginUser", user);
        response.sendRedirect("./");
    }
}

src/chapter6/controller/ManagementServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import chapter6.beans.UserBranchDepartment;
import chapter6.service.UserService;

	@WebServlet(urlPatterns = { "/management" })
	public class ManagementServlet extends HttpServlet {

		@Override
		protected void doGet(HttpServletRequest request, HttpServletResponse response)
				throws IOException, ServletException {

			List<UserBranchDepartment> userList = new UserService().select();

			request.setAttribute("userList", userList);
			request.getRequestDispatcher("/management.jsp").forward(request, response);
		    }

	}

src/chapter6/controller/MessageServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.Message;
import chapter6.beans.User;
import chapter6.service.MessageService;

@WebServlet(urlPatterns = { "/message" })
public class MessageServlet extends HttpServlet {

	@Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws IOException, ServletException {

		request.getRequestDispatcher("message.jsp").forward(request, response);
		}

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
    		throws IOException, ServletException {

    	HttpSession session = request.getSession();

    	List<String> errorMessages = new ArrayList<String>();

    	String title = request.getParameter("title");
        String category = request.getParameter("category");
        String text = request.getParameter("text");

        if (!(isValid(text,title,category, errorMessages))){
        	session.setAttribute("errorMessages", errorMessages);
            session.setAttribute("title",title );
            session.setAttribute("category",category);
            session.setAttribute("text", text);
            response.sendRedirect("./message");
            return;
        }

        Message message = new Message();
        message.setTitle(title);
        message.setCategory(category);
        message.setText(text);

        User user = (User) session.getAttribute("loginUser");
        message.setUserId(user.getId());

        new MessageService().insert(message);
        response.sendRedirect("./");
    }

    private boolean isValid(String text, String title,String category,List<String> errorMessages) {

    	if (StringUtils.isBlank(title)){
    		errorMessages.add("件名を入力してください");
    	}

    	if (30<= title.length()){
    		errorMessages.add("件名を30文字以下で、入力してください");
    	}

    	if (StringUtils.isBlank(category)) {
    		errorMessages.add("カテゴリー名を入力してください");
    	}

    	if (10 < category.length()) {
    		errorMessages.add("カテゴリ－名は10文字以下で入力してください");
    	}

    	if (StringUtils.isBlank(text)) {
    		errorMessages.add("本文を入力してください");
    	}

    	if (1000 <= text.length()) {
    		errorMessages.add("1000文字以下で、本文を入力して下さい");
    	}

    	if (errorMessages.size() != 0) {
    		return false;
        }

        return true;
    }

}

src/chapter6/controller/SettingServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.Branch;
import chapter6.beans.Department;
import chapter6.beans.User;
import chapter6.service.BranchService;
import chapter6.service.DepartmentService;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/setting" })
public class SettingServlet extends HttpServlet {

	@Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws IOException, ServletException {

		User user = null;

		String str = request.getParameter("userId");
		if(!StringUtils.isEmpty(str) && str.matches("[0-9]{1,9}")){
			int userId = Integer.valueOf(str);
			user = new UserService().select(userId);
		}

		if (user == null) {
			List<String>errorMessages = new ArrayList<String>();
			errorMessages.add("不正なパラメーターが入力されました");
			HttpSession session = request.getSession();
			session.setAttribute("errorMessages", errorMessages);
			response.sendRedirect("./management");
			return;
		}

		List<Branch>branches = new BranchService().select();
		List<Department>departments = new DepartmentService().select();

		request.setAttribute("branches",branches);
		request.setAttribute("departments",departments);
		request.setAttribute("user",user);

		request.getRequestDispatcher("setting.jsp").forward(request, response);

	}

	@Override
	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws IOException, ServletException {

		List<String> errorMessages = new ArrayList<String>();

		User user = getUser(request);

		if (!isValid(user, errorMessages)) {
			request.setAttribute("errorMessages", errorMessages);
			request.setAttribute("branches",new BranchService().select());
			request.setAttribute("departments",new DepartmentService().select());
			request.setAttribute("user",user);
			request.getRequestDispatcher("setting.jsp").forward(request, response);
			return;
		}

		new UserService().update(user);
		response.sendRedirect("./management");
	}

	private User getUser(HttpServletRequest request) throws IOException, ServletException {

		User user = new User();

		user.setId(Integer.valueOf(request.getParameter("userId")));
		user.setAccount(request.getParameter("account"));
		user.setName(request.getParameter("name"));
		user.setPassword(request.getParameter("password"));
		user.setConfirmationPassword(request.getParameter("confirmationPassword"));
		user.setBranchId(Integer.valueOf(request.getParameter("branchId")));
		user.setDepartmentId(Integer.valueOf(request.getParameter("departmentId")));
		return user;
	}

	private boolean isValid(User user, List<String> errorMessages) {

		String account = user.getAccount();
		String name = user.getName();
		String password = user.getPassword();
		String confirmationPassword = user.getConfirmationPassword();
		String branchId = String.valueOf(user.getBranchId());
		String departmentId = String.valueOf(user.getDepartmentId());

		User userCheck = new UserService().select(account);

        if (StringUtils.isEmpty(name)) {
        	errorMessages.add("名前を入力してください");
        }else  if (!StringUtils.isEmpty(name) && (10 < name.length())) {
            errorMessages.add("名前は10文字以下で入力してください");
        }

		if (StringUtils.isEmpty(account)) {
			errorMessages.add("アカウント名を入力してください");
	    }else if (6 > account.length() || 20 < account.length()) {
			errorMessages.add("アカウント名は6文字以上、20文字以下で入力してください");
	    }else if (!(account.matches("^[A-Za-z0-9]+$"))) {
			errorMessages.add("アカウント名は半角英数字で入力してください");
		}

		if (!(StringUtils.isEmpty(password) || password == null)) {
			if(6 > password.length() || 20 < password.length()) {
				errorMessages.add("パスワードは6文字以上、20文字以下で入力してください");
			}else if (6 > confirmationPassword.length() || 20 < confirmationPassword.length()) {
				errorMessages.add("確認用パスワードは6文字以上、20文字以下で入力してください");
			}
		}

		if(!(password.equals(confirmationPassword)) ){
            errorMessages.add("入力したパスワードと確認用パスワードが一致しません");
        }

		if (StringUtils.isEmpty(branchId)) {
			errorMessages.add("支社を選択してください");
		}

		if (StringUtils.isEmpty(departmentId)) {
			errorMessages.add("部署を選択してください");
		}

		//本社　人事部と情報管理部
        if(Integer.valueOf(branchId)==1 && (Integer.valueOf(departmentId) ==3)){
         	errorMessages.add("支社と部署が異なります");
        }
        if(Integer.valueOf(branchId)==1 && (Integer.valueOf(departmentId) ==4)){
         	errorMessages.add("支社と部署が異なります");
        }
         //A社　営業部と技術部
        if(Integer.valueOf(branchId)==2 && (Integer.valueOf(departmentId) ==1)){
         	errorMessages.add("支社と部署が異なります");
        }
        if(Integer.valueOf(branchId)==2 && (Integer.valueOf(departmentId) ==2)){
         	errorMessages.add("支社と部署が異なります");
        }
         //B支社　営業部と技術部
        if(Integer.valueOf(branchId)==3 && (Integer.valueOf(departmentId) ==1)){
         	errorMessages.add("支社と部署が異なります");
        }
        if(Integer.valueOf(branchId)==3 && (Integer.valueOf(departmentId) ==2)){
         	errorMessages.add("支社と部署が異なります");
        }
         //C支社　営業部と技術部
        if(Integer.valueOf(branchId)==4 && (Integer.valueOf(departmentId) ==1)){
         	errorMessages.add("支社と部署が異なります");
        }
        if(Integer.valueOf(branchId)==4 && (Integer.valueOf(departmentId) ==2)){
         	errorMessages.add("支社と部署が異なります");
        }
          //ユーザーの重複
        if(userCheck != null){
        	if(userCheck.getId() != user.getId()) {
        		errorMessages.add("アカウントが重複しています");
        	}
        }

		if (errorMessages.size() == 0) {
			return true;
		} else {
			return false;
		}
	}

}

WebContent/home.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ホーム画面</title>

<script type="text/javascript">
<!--

function check(){

	if(window.confirm('削除しますか？')){ //
		return true;
	}
	else{ // 「キャンセル」時の処理
		return false; // 送信を中止
	}
}

// -->
</script>

</head>
<body>
	<div class="main-contents">

		<c:if test="${ empty loginUser }">
			<a href="signup">新規登録</a>
			<a href="login">ログイン</a>
		</c:if>

		<c:if test="${ not empty loginUser }">
			<a href="message">新規投稿</a>

			<c:if test = "${loginUser.branchId == 1 and loginUser.departmentId ==1}">
			<a href="management">ユーザー管理</a>
			</c:if>>

			<a href="logout">ログアウト</a>
		</c:if>

		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="errorMessage">
						<li><c:out value="${errorMessage}" />
					</c:forEach>
				</ul>
			</div>
        </c:if>

		<c:remove var="errorMessages" scope="session"/>

		<form action="/" method="get">
			<label>
			日付<input type="date" name="start" value="${start}" >～<input type="date" name="end" value="${end}">
			</label>
			<br>
			<label>
			カテゴリ<input name="category" id="name" value="${category}"/> <input type="submit" value="絞込み">
			</label>
		</form>

		<div class="messages">
			<c:forEach items="${messages}" var="message">

				<div class="message">

					<div class="account-name">
						<span class="name"> <c:out value="${message.name}" />
						</span> <span class="account"> <c:out value="${message.account}" />
						</span>
					</div>

					<div class="title">
						<c:out value="${message.title}" />
					</div>

					<div class="category">
						<c:out value="${message.category}" />
					</div>

					<c:forEach  items="${message.splitedText}" var="m">
						<div class="text">
							<c:out value="${m}" />
						</div>
					</c:forEach>

					<div class="date">
						<fmt:formatDate value="${message.createdDate}"
							pattern="yyyy/MM/dd HH:mm:ss" />
					</div>
				</div>

				<c:if test="${loginUser.id == message.userId}" >
					<form action = "deleteMessage" method ="post" onSubmit="return check()">
						<input type="hidden" name="messageId" value="${message.id}">
						<input type="submit" value="削除">
					</form>
				</c:if>


				<div class="form-area">

					<form action="comment" method="post">
						コメント入力欄<br />
						<textarea name="text" cols="100" rows="5" class="tweet-box"></textarea>
						<input type="hidden" name="messageId" value="${message.id}" />
						<input type="submit" value="投稿"><br />
					</form>

					<div class="comments">
						<c:forEach items="${comments}" var="comment">

							<c:if test="${message.id == comment.messageId }">

								<div class="comment">

									<div class="account-name">
										<span class="account"> <c:out value="${comment.account}" /></span>
										<span class="name"> <c:out value="${comment.name}" /></span>
									</div>

									<c:forEach  items="${comment.splitedText}" var="c">
										<div class="text">
											<c:out value="${c}" />
										</div>
									</c:forEach>

									<div class="date">
										<fmt:formatDate value="${comment.createdDate}" pattern="yyyy/MM/dd HH:mm:ss" />
									</div>

								</div>
								<c:if test="${loginUser.id == comment.userId }">
									<form action = "deleteComment" method ="post" onSubmit="return check()">
										<input type="hidden" name="commentId" value="${comment.id}">
										<input  type="submit" value="削除">
									</form>
								</c:if>
							</c:if>
						</c:forEach>
					</div>
				</div>
			</c:forEach>
		</div>

		<div class="copyright">Copyright(c)usui_arisa</div>

	</div>
</body>
</html>

WebContent/login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>ログイン画面</title>
    </head>
    <body>

        <div class="main-contents">

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="errorMessage">
                            <li><c:out value="${errorMessage}" />
                        </c:forEach>
                    </ul>
                </div>
            </c:if>

            <c:remove var="errorMessages" scope="session"/>


            <form action="login" method="post" ><br />
                <label for="account">アカウント</label>
                <input name="account" id="account" value="${account}"/> <br />

                <label for="password">パスワード</label>
                <input name="password" type="password" id="password"/> <br />

                <input type="submit" value="ログイン" /> <br />
            </form>

            <div class="copyright"> Copyright(c)usui_arisa</div>
        </div>
    </body>
</html>

WebContent/management.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>ユーザー管理画面</title>

<script type="text/javascript">
<!--

function check(){

	if(window.confirm('変更しますか？')){ //

		return true;

	}
	else{ // 「キャンセル」時の処理

		return false; // 送信を中止
	}

}

// -->
</script>
</head>
<body>
	<div class="main-contents">

		<a href="./">ホーム</a>
	 	<a href="signup">ユーザー新規登録</a>

	</div>

	<c:if test="${ not empty errorMessages }">
		<div class="errorMessages">
			<ul>
				<c:forEach items="${errorMessages}" var="errorMessage">
					<li><c:out value="${errorMessage}" />
				</c:forEach>
			</ul>
		</div>
	</c:if>

	<c:remove var="errorMessages" scope="session"/>

	<c:forEach items="${userList}" var="user">

        <div class="account">><c:out value="${user.account}" /></div>

        <div class="name"><c:out value="${user.name}" /></div>

        <div class="branchName"><c:out value="${user.branchName}" /></div>

        <div class="departmentName"><c:out value="${user.departmentName}" /> </div>

        <c:if test="${user.isStopped==1 }">
        	<div class="isStopped"><c:out value="停止中"/></div>
        </c:if>

        <c:if test="${user.isStopped==0 }">
        	<div class="isStopped"><c:out value="復活中"/></div>
        </c:if>

		<form action="setting" method="get">
        	<input type="hidden" name="userId" value="${ user.id }" />
        	<input type="submit" value="編集">
        </form>

		<form action="stop" method="post" onSubmit="return check()">

			<c:if test="${user.id != loginUser.id}">
			<c:if test="${user.isStopped==1}">
				<input type="hidden" name="userId" value="${user.id}">
				<input type="hidden" name="isStopped" value="0">
				<input type="submit" value="復活" >
			</c:if>
			</c:if>

			<c:if test="${user.id != loginUser.id}">
			<c:if test="${user.isStopped ==0}">
				<input type="hidden" name="userId" value="${user.id}">
				<input type="hidden" name="isStopped" value="1">
				<input type="submit" value="停止" >
			</c:if>
			</c:if>

		</form>

		<div class="copyright">Copyright(c)usui_arisa</div>

	</c:forEach>
</body>
</html>

WebContent/message.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>新規投稿画面</title>
    </head>
    <body>
        <div class="main-contents">

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="errorMessage">
                            <li><c:out value="${errorMessage}" />
                        </c:forEach>
                    </ul>
                </div>
            </c:if>

			<c:remove var="errorMessages" scope="session"/>

            <form action="message" method="post"><br />
            	<a href="./">ホーム</a>

                <label for="title">件名</label>
                <input name="title" id="title" value="${title}"/><br />

                <label for="category">カテゴリー</label>
                <input name="category" id="category" value="${category}" /> <br />

                <label for="text">投稿内容</label>
                <textarea name="text" cols="35" rows="5" id="text">${text}</textarea> <br />
                <input type="submit" value="登録" /> <br />
            </form>

			<c:remove var="title" scope="session"/>
			<c:remove var="category" scope="session"/>
			<c:remove var="text" scope="session"/>

            <div class="copyright">Copyright(c)usui_arisa</div>
        </div>
    </body>
</html>

WebContent/setting.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>ユーザー編集画面</title>

    </head>
    <body>

		<div class="main-contents">
			<a href="management">ユーザー管理</a>
		</div>

		<c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="errorMessage">
                            <li><c:out value="${errorMessage}" />
                        </c:forEach>
                    </ul>
                </div>
            </c:if>

            <c:remove var="errorMessages" scope="session"/>


		<form action="setting" method="post">

			<label for="account">アカウント</label>
			<input name="account" value="${user.account}"/><br />

			<label for="password">パスワード</label>
			<input name="password" type="password" /> <br />

			<label for="confirmationPassword">確認用パスワード</label>
			<input name="confirmationPassword" type="password"/> <br />

			<label for="name">名前</label>
			<input name="name" value="${user.name }" /><br />

			<p>支社</p>
			<select name="branchId">
				<c:if test="${user.id != loginUser.id}">
					<c:forEach items="${branches}" var="branch">
						<option value="${branch.id}"<c:if test ="${branch.id == user.branchId}">selected</c:if>>${branch.name}</option>
					</c:forEach>
				</c:if>

				<c:if test="${user.id == loginUser.id}">
					<c:forEach items="${branches}" var="branch">
						<c:if test="${branch.id == user.branchId }"><option value="${branch.id}">${branch.name}</option></c:if>
					</c:forEach>
				</c:if>
			</select>



			<p>部署<p>
			<select name="departmentId">
				<c:if test="${user.id != loginUser.id}">
					<c:forEach items="${departments}" var="department">
						<option value="${department.id}"<c:if test = "${department.id == user.departmentId}">selected</c:if>>${department.name}</option>
					</c:forEach>
				</c:if>

				<c:if test="${user.id == loginUser.id}">
					<c:forEach items="${departments}" var="department">
						<c:if test="${department.id == user.departmentId }"><option value="${department.id}">${department.name}</option></c:if>
					</c:forEach>
				</c:if>
			</select><br>


			<input type="hidden" name="userId" value="${user.id}">
			<input type="submit" value="更新" /> <br />
		</form>

		<div class="copyright"> Copyright(c)usui_arisa</div>

    </body>
</html>